#
# Copyright 2020 DXOS.org
#

name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: dxos/jest-reporter-action@0.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: "yarn test --coverage"
